---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: Metrics
'on':
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 1  # Weekly on Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: GitHub metrics SVG image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Brisbane/Australia
          plugin_achievements: 'no'
          plugin_achievements_limit: 0
          plugin_achievements_secrets: 'no'
          plugin_activity: 'no'
          plugin_followup: 'yes'
          plugin_followup_sections: repositories, user
          plugin_languages: 'yes'
          plugin_languages_details: bytes-size, percentage
          plugin_notable: 'no'
          plugin_notable_filter: stars:>1000
          plugin_notable_repositories: 'yes'
          plugin_stargazers: 'no'
